document.write ('<!--/* OpenX JavaScript tag */-->\n');
document.write ('\n');
document.write ('<!-- /*\n');
document.write (' * The tag in this template has been generated for use on a\n');
document.write (' * non-SSL page. If this tag is to be placed on an SSL page, change the\n');
document.write (' * ');
document.write ("'");
document.write ('https://us-ads.openx.net/...');
document.write ("'");
document.write ('\n');
document.write (' * to\n');
document.write (' * ');
document.write ("'");
document.write ('https://us-ads.openx.net/...');
document.write ("'");
document.write ('\n');
document.write (' */ -->\n');
document.write ('\n');
document.write ('<script type="text/javascript">\n');
document.write ('if (!window.OX_ads) { OX_ads = []; }\n');
document.write ('OX_ads.push({ "auid" : "538020939" });\n');
document.write ('</script>\n');
document.write ('<script type="text/javascript">\n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt src="https://us-ads.openx.net/w/1.0/jstag"><\\');
document.write ('/scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write (');\n');
document.write ('</script>\n');
document.write ('<noscript><iframe id="3a83dd2fe3" name="3a83dd2fe3" src="https://us-ads.openx.net/w/1.0/afr?auid=538020939&cb=2122866929" frameborder="0" scrolling="no" width="300" height="600"><a href="https://us-ads.openx.net/w/1.0/rc?cs=3a83dd2fe3&cb=2122866929" ><img src="https://us-ads.openx.net/w/1.0/ai?auid=538020939&cs=3a83dd2fe3&cb=2122866929" border="0" alt=""></a></iframe></noscript>\n');
document.write ('\n');
document.write ('       <noscript class="MOAT-comcastapn56341864860?moatClientLevel1=OpenX&amp;moatClientLevel2=Comcast/OpenX_201507_SIG_300_NATL&amp;moatClientLevel3=300x250_RM_OpenX_SI_09222015&amp;moatClientSlicer1=x32&amp;moatClientSlicer2=comcast.net/login_secure/notve/L30"></noscript>\n');
document.write ('<script src="https://z.moatads.com/comcastapn56341864860/moatad.js#moatClientLevel1=OpenX&moatClientLevel2=Comcast/OpenX_201507_SIG_300_NATL&moatClientLevel3=300x250_RM_OpenX_SI_09222015&moatClientSlicer1=x32&moatClientSlicer2=comcast.net/login_secure/notve/L30" type="text/javascript"></script>\n');
document.write ('<script>\n');
document.write ('try{\n');
document.write ('var x32adtag = "Comcast/OpenX_201507_SIG_300_NATL".split("/")[1];\n');
document.write ('var adtag_x32 = "camp_" + x32adtag + "_creativeId_300x250_RM_OpenX_SI_09222015";\n');
document.write ('}\n');
document.write ('catch(e){}\n');
document.write ('</script>\n');
document.write ('     ');
